name: Deploy Clustering Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'services/clustering_service/**'
      - '.github/workflows/deploy-clustering-service.yml'
      - '.github/workflows/_deploy_service.yml'

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/_deploy_service.yml
    with:
      service_name: 'clustering-service'
      service_path: 'services/clustering_service'
      ecr_repo_name: 'centinela-clustering-service'
      ecr_resource_name: 'repo'
    secrets: inherit
