name: Deploy Knowledge Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'services/knowledge-service/**'
      - '.github/workflows/deploy-knowledge-service.yml'
      - '.github/workflows/_deploy_service.yml'

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/_deploy_service.yml
    with:
      service_name: 'knowledge-service'
      service_path: 'services/knowledge-service'
      ecr_repo_name: 'knowledge-service'
      ecr_resource_name: 'app_repo'
    secrets: inherit
