name: Deploy Orchestrator

on:
  push:
    branches: [ "main" ]
    paths:
      - 'services/orchestrator/**'
      - '.github/workflows/deploy-orchestrator.yml'
      - '.github/workflows/_deploy_service.yml'

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/_deploy_service.yml
    with:
      service_name: 'orchestrator'
      service_path: 'services/orchestrator'
      ecr_repo_name: 'centinela-orchestrator'
      ecr_resource_name: 'repo'
    secrets: inherit
