name: Deploy Chat Model

on:
  push:
    branches: [ "main" ]
    paths:
      - 'services/chat_model/**'
      - '.github/workflows/deploy-chat-model.yml'
      - '.github/workflows/_deploy_service.yml'

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/_deploy_service.yml
    with:
      service_name: 'chat-model'
      service_path: 'services/chat_model'
      ecr_repo_name: 'centinela-chat-model'
      ecr_resource_name: 'repo'
    secrets: inherit
