name: Deploy Strategist

on:
  push:
    branches: [ "main" ]
    paths:
      - 'services/strategist/**'
      - '.github/workflows/deploy-strategist.yml'
      - '.github/workflows/_deploy_service.yml'

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/_deploy_service.yml
    with:
      service_name: 'strategist'
      service_path: 'services/strategist'
    secrets: inherit
