name: Deploy Gateway

on:
  push:
    branches: [ "main" ]
    paths:
      - 'services/gateway/**'
      - '.github/workflows/deploy-gateway.yml'
      - '.github/workflows/_deploy_service.yml'

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/_deploy_service.yml
    with:
      service_name: 'gateway'
      service_path: 'services/gateway'
      ecr_repo_name: 'centinela-gateway'
      ecr_resource_name: 'repo'
    secrets: inherit
